Базовая стилизация
zvovasteach/maria-device-html1 pull request #3
Opened 2024-07-09 19:11 UTC by MariaRodkevich

2024-07-19 12:23 UTC, evovas requested changes

2024-07-19 12:23 UTC, evovas commented on index.html
>      <a class="phone" href="+78128121212">+7 (812) 812-12-12</a>
`href="tel:+78128121212"`

2024-07-19 12:23 UTC, evovas commented on css/style.css
> +.navigation-link-more {
Название класса неудачное, я бы использовал slider-link

2024-07-19 12:23 UTC, evovas commented on css/style.css
> +}
Это глобальный селектор по тегу, они запрещены. Добавь адресу класс и стилизуй по нему

2024-07-19 12:23 UTC, evovas commented on css/style.css
> +}
Этот класс всегда пишется в самом конце css файла

2024-09-24 12:11 UTC, evovas requested changes

2024-09-24 12:11 UTC, evovas commented on index.html
> +      <span class="one">01</span>
1. Эта единица относится к элементу списка, у других слайдов 02 и 03 соответственно. 
2. Класс one не подходит, это скорее counter или что-то такое

2024-09-24 12:11 UTC, evovas commented on index.html
> +              </ol>
Кнопки переключения слайдов не могут быть частью какого-то слайда (элемента списка). Вынеси их вниз из списка слайдов.

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +    url("../fonts/rubik/rubik-400.woff") format("woff");
Если на курсе тебе не дали шрифты в формате woff (у тебя нет файла), то нужно удалить упоминание. Да и вообще формат woff устарел и все современные браузеры поддерживают woff2.

2024-09-24 12:11 UTC, evovas commented on index.html
>            <p>Самая длинная палка для селфи доступна в нашем магазине. Восемь (Восемь, Карл!) метров длиной и весом всего 5 кг.</p>
Так же нет класса, значит и нет стилизации

2024-09-24 12:11 UTC, evovas commented on index.html
>            <p>Мотивирующие фитнес-браслеты помогут найти в себе силы не пропускать занятия и соблюдать диету.</p>
Нет класса, значит и нет стилизации

2024-09-24 12:11 UTC, evovas commented on index.html
>        <ul class="service-description">
Тоже можно скрыть другие неактивные "сервисы" так же как поступили со слайдами и классом с active

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +.rare-service-container {
1. Ты забыла про класс container тут и далее. Используй его для центрирования и задания ширины.
2. Тут задан отступ снизу. А должен быть отступ сверху у следующего элемента.

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +.about-title {
Тут не обнулила стандартные отступы. Так же не обнулила их в `about-description`, `paragraph-list`, `title-contacts` и `paragraph-list-name`

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  padding-bottom: 144px;
Этот отступ это не падинг снизу, а маргин сверху у формы с почтой

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  overflow-x: auto;
лишнее свойство

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  list-style-type: none;
Просто  list-style: none;

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  font-weight: bold;
Задавать вес текста нужно в числах

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  text-align: flex-start;
Текст не может быть выровнен с помощью значения flex-start

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  line-height: 167%
Забыла точку с запятой

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  width: 253px;
Ширины у плейсхолдера не может быть

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  padding-left: 10px;
Я сейчас понял, что и других свойств кроме цвета быть не может, плейсхолдер совпадает с вводом текста

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  width: 253px;
Попробуй добиться ширины этой кнопки без свойства width, а с помощью отступов

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +.adress-footer {
Опечатка в слове

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  text-decoration: none;
Два взаимоисключающих свойства

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +  display: flex;
А зачем тут дисплей флекс?)

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +
Это все можно объединить в один класс, ты же прям повторяешься... в такие моменты ты должна всегда думать: "А зачем копировать, если можно сделать в одном месте".

2024-09-24 12:11 UTC, evovas commented on css/style.css
> +}
Не понимаю зачем нужна эта обертка...

2024-09-26 14:32 UTC, evovas requested changes

2024-09-26 14:32 UTC, evovas commented on index.html
> +              <dl class="container-specific">
Зачем ты оставила эти обертки здесь?

2024-09-26 14:32 UTC, evovas commented on index.html
> +          <span class="counter">01</span>
В других слайдах тоже нужно добавить номера

2024-09-26 14:32 UTC, evovas commented on index.html
> +      </button>
Все же это похоже на список, можно обернуть с список

2024-09-26 14:32 UTC, evovas commented on css/style.css
> +    url("../fonts/rubik/rubik-400.woff2") format("woff2"),
Ты просто удалила ссылку на woff шрифты, но на строке с woff2 осталась запятая, которая приводит к ошибке

2024-09-26 14:32 UTC, evovas commented on css/style.css
> +.rare-service-container {
Почему у тебя на исправленных местах ширина контейнера переопределяется на 1140 пикселей?

2024-09-26 14:32 UTC, evovas commented on css/style.css
> +  width: 253px;
Немного не получилось
![CleanShot 2024-09-26 at 16 25 33@2x](https://github.com/user-attachments/assets/e7c8d98a-0a6b-4f21-a56a-32099ac68558)

2024-09-26 14:32 UTC, evovas commented on css/style.css
> +  justify-content: center;
Два раза повторила свойство

2024-09-26 14:32 UTC, evovas commented on css/style.css
> +  border: solid white;
бордер всегда должен состоять из трех частей: толщина, стиль, цвет

2024-09-27 17:50 UTC, MariaRodkevich commented on index.html
> +              <dl class="container-specific">
ты имеешь в виду<div class="container-slider-more"> ?

2024-09-28 14:40 UTC, MariaRodkevich commented on index.html
> +              <dl class="container-specific">
Они нужны, чтобы правильно расположить на странице термин и описание. Я задала div класс и сделала их флексом column reverse чтобы сначала шло описание, а потом термин, не меняя порядок в разметке.

2024-09-28 14:48 UTC, MariaRodkevich commented on index.html
> +          <span class="counter">01</span>
Добавила.

2024-09-28 15:14 UTC, MariaRodkevich commented on index.html
> +      </button>
Сделала списком.

2024-09-28 15:16 UTC, MariaRodkevich commented on css/style.css
> +    url("../fonts/rubik/rubik-400.woff2") format("woff2"),
Исправила.

2024-09-28 15:23 UTC, MariaRodkevich commented on css/style.css
> +  justify-content: center;
Все поисправляла.

2024-09-28 15:28 UTC, MariaRodkevich commented on css/style.css
> +  border: solid white;
Добавила толщину.

2024-10-02 16:23 UTC, evovas commented on css/style.css
> +  width: 253px;
По самому инпуту, тоже убери высоту у него и с помощью отступов сделай реализацию стайлгайда
![CleanShot 2024-10-02 at 18 21 14@2x](https://github.com/user-attachments/assets/148498b3-634b-4f46-b8ba-8afb43500b91)

2024-10-02 16:28 UTC, evovas commented on index.html
> +          <span class="counter">01</span>
Я в сразу не заметил, но тут грубая ошибка в том, что у тебя `span` является ребенком `ol`, так нельзя, внутри `ul` или `ol` непосредственными детьми могут быть только `li`. Этот номер это часть "слайда", поэтому нужно перенести их внутрь слайда.

2024-10-02 16:40 UTC, evovas commented on index.html
> +          <span class="counter visually-hidden">02</span>
Вот тебе даже приходится скрывать их с помощью `visually-hidden`, хотя при смене слайдов они должны так же автоматически отображаться вместе с соотвествующим слайдом.

2024-10-02 16:40 UTC, evovas commented on index.html
> +              </ul>
Ты же уже убирала кнопки из слайда и опять их вернула. Еще раз, если я включу второй слайд с фитнес-браслетом, то кнопки исчезнут, так как они в разметке располагаются внутри первого слайда. Этот список должен быть рядом с кнопками предыдущего и следующего слайда.

2024-10-02 16:40 UTC, evovas commented on css/style.css
> +  list-style-type: none;
Не исправила

2024-10-02 16:40 UTC, evovas commented on index.html
> +              <dl class="container-specific">
Это касалось строк кода _Comment on lines 82 to 93_ То есть списка `ol` c пустыми `li`

2024-10-02 18:47 UTC, evovas requested changes

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +<div class="products-pagination-download-container container">
1. `products-pagination-download-container` оочень странное название класса
2. `container` тут быть не может. Ты отменила в классе `products-pagination-download-container` все его свойства. `container` должен быть внутри и отвечать за ширину и центрирование, а сейчас это делает `products-container-inner`

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +        <div class="filter-container-info">
Отступ слева который ты задаешь каждому элементу в виде маргина, можно задать в виде падинга для `filter-container-info`

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +        <button class="service-button" type="submit">Показать</button>
Вот ты искала что у тебя форма широкая, вот эта кнопка, задана ширина в 280 пикселей
![CleanShot 2024-10-02 at 20 19 00@2x](https://github.com/user-attachments/assets/6924db7b-4942-4f8e-9099-1771a09de3d8)

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +        <hr class="line">
Не, `<hr>` тут не надо. Просто используй бордер у филдсетов

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +  <div class="filter-container">
По фильтру дам потом комментарии подробные, когда уже будешь его полностью делать.

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +<div class="products-wrap container">
1. `container` тут не имеет смысла, его стили не используются
2. Тут можно задать общий падинг

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +<div class="download-pagination-wrap">
Это лишняя обертка

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +  </section>
_Closing tag matches nothing_

2024-10-02 18:47 UTC, evovas commented on catalog.html
> +<div class="pagination-controls">
Как говорил ранее, внутри `ul` не может быть непосредственных детей кроме `li`

2024-10-02 18:47 UTC, evovas commented on css/style.css
> +  font-family: "Raleway";
Кстати, у каждого свойства `font-family` должно быть указано через запятую  `sans-serif` (без засечек) или `serif` (с засечками)

2024-10-02 18:47 UTC, evovas commented on css/style.css
> +.catalog-monopods {
Нельзя привязываться к смыслу товара в каталоге. Другие страницы с другими продуктами будут выглядеть одинаково. А значит упоминание монопода на странице с браслетами будет странным. Из всех классов на странице убери упоминания моноподов.

2024-10-02 18:47 UTC, evovas commented on css/style.css
> +.product-card div {
Неочевидно на самом деле. Лучше задай этому диву класс и стилизуй по нему.

2024-10-03 12:17 UTC, MariaRodkevich commented on css/style.css
> +  width: 253px;
Теперь выглядит по стайлгайду

2024-10-03 17:21 UTC, MariaRodkevich commented on index.html
> +          <span class="counter">01</span>
Убрала span внутрь слайдера, пришлось поместить его в контейнер и сделать абсолютом.

2024-10-03 17:22 UTC, MariaRodkevich commented on index.html
> +          <span class="counter visually-hidden">02</span>
Больше не visually-hidden.

2024-10-03 17:23 UTC, MariaRodkevich commented on index.html
> +              </ul>
Вернула.

2024-10-04 13:16 UTC, MariaRodkevich commented on catalog.html
> +        <div class="filter-container-info">
Видимо, ты имел в виду падинг для main-inner? У дочерних элементов filter-container-info маргинов нет, там только gap. В общем, сделала, как поняла (заменила все марджины на 1 паддинг main-inner).

2024-10-04 14:13 UTC, MariaRodkevich commented on catalog.html
> +<div class="products-wrap container">
1 - ok
2 - если задать паддинг, то все поломается внутри грида. Можно только марджин задать, но у меня там gap между флекс-элементами, поэтому пока оставлю так до твоих следующих комментариев. Вообще у меня по пикселям ничего не сходится с макетом, если брать за эталон хедер (таким как он есть сейчас).

2024-10-11 16:14 UTC, evovas requested changes

2024-10-11 16:14 UTC, evovas commented on css/style.css
> +  margin 0;
Пропустила двоеточие

2024-10-11 16:14 UTC, evovas commented on index.html
> +          <span class="counter">01</span>
```
<div class="counter-wrapper">
  <span class="counter">01</span>
</div>
```

Обертка `counter-wrapper` лишняя. Без нее прекрасно можно сделать оставив просто `<span class="counter">01</span>`

2024-10-11 16:14 UTC, evovas commented on index.html
> +      <section class="devices">
Element `<section>` is not closed

2024-10-11 16:14 UTC, evovas commented on catalog.html
> +          </form>
Closing tag matches nothing

2024-10-11 16:14 UTC, evovas commented on css/style.css
> +}
Проблема `z-index: -1` в том, что для использования его на декоративных элементах нет ничего плохого, а вот если элемент содержит интерактивные элементы, то с этими элементами исчезает возможность взаимодействовать (ссылки в хедере стали некликабельными). `z-index: -1` можно сравнить с помещением под стекло чего-то, если кнопку положить под стекло на нее нельзя нажимать, а если фотографию, то ее видно и все хорошо.

2024-10-11 16:14 UTC, evovas commented on css/style.css
> +  font-family: "Rubik", sans-serif;
Кстати  если не задать `position: absolute` или `position: relative` то свойства типа right не действуют никак

2024-10-11 16:14 UTC, evovas commented on catalog.html
> +          <span class="filter-sorting">Сортировка:</span>
У тебя **Фильтр:** должен относиться и находиться в ращзметке с фильтром, а тут он у тебя относится к сортировке. Вот правильная схема
![CleanShot 2024-10-11 at 17 29 02@2x](https://github.com/user-attachments/assets/db427ed9-0044-42d9-a888-620c2cd97f38)

2024-10-11 16:14 UTC, evovas commented on catalog.html
> +        <hr class="line">
Все же это должен быть бордер у `fieldset`, а не у `legend`

2024-10-11 16:14 UTC, evovas commented on catalog.html
> +        <fieldset class="product-filter-group">
Ты не обнулила маргины у филдсетов, из-за этого у каждого филдсета слева отступ в 2 пикселя

2024-10-11 16:14 UTC, evovas commented on css/style.css
> +
Из-за этого отступа у тебя слева белая полоска, а серый фон в каталоге должен быть на всю ширину. Зачем этот отступ нужен?

2024-10-11 16:14 UTC, evovas commented on catalog.html
> +<div class="products-wrap container">
Я имею вот такой падинг должен быть:
![CleanShot 2024-10-11 at 17 56 08@2x](https://github.com/user-attachments/assets/0e085f86-d3f9-4c72-966b-745ccff6615f)

2024-10-13 11:15 UTC, MariaRodkevich commented on css/style.css
> +}
Поменяла z-index у других элементов, теперь ссылки доступны.

2024-10-13 12:50 UTC, MariaRodkevich commented on catalog.html
> +        <fieldset class="product-filter-group">
1. У филдсетов встроенный верхний бордер не такой, как мне нужен, он прерывается текстом и мне не подходит. Поэтому я сделала бордер псевдоклассом.
2. Ок.

2024-10-13 13:00 UTC, MariaRodkevich commented on css/style.css
> +
Не нужен.

2024-10-13 13:43 UTC, MariaRodkevich commented on catalog.html
> +          <span class="filter-sorting">Сортировка:</span>
Текст Фильтр теперь абсолют, по-другому он никак не хотел вставать на место.

2024-10-27 20:23 UTC, evovas requested changes

2024-10-27 20:23 UTC, evovas commented on catalog.html
> +  <span class="filter-sorting">Фильтр:</span>
1. "Фильтр:" относится непосредственно к section "catalog-products" и должен быть внутри секшена
2. Вот тут скажу, и по всему проекту это относится, отрицательные маргины это максимальное исключение и трюк, который применяется в исключительных случаях. Ты же в этой части и паре других мест используешь его там, где можно решить проблему другим более правильным способом.

2024-10-27 20:23 UTC, evovas commented on catalog.html
> +        <hr class="line">
_У филдсетов встроенный верхний бордер не такой, как мне нужен, он прерывается текстом и мне не подходит. Поэтому я сделала бордер псевдоклассом._
Кажется вот этот твой комментарий относился в этому моему замечанию. Так переопредели стандартный. В общем нужно сделать бордер у fieldset, а не псевдоэлемент.

2024-10-27 20:23 UTC, evovas commented on css/style.css
> +}
Каталог товаров всё так же недоступен, доступны несколько пикселей сверху надписи

2024-10-29 09:16 UTC, MariaRodkevich commented on catalog.html
> +  <span class="filter-sorting">Фильтр:</span>
1. Теперь фильтр непосредственно внутри секции, но у секции новое название - <section class="filter-products-section">.
2. Оставила отрицательные значения только в местах, где абсолют.

2024-10-29 13:20 UTC, MariaRodkevich commented on catalog.html
> +          <span class="filter-sorting">Сортировка:</span>
Реализовала твою схему гридами.

2024-11-01 12:13 UTC, evovas approved these changes

2024-11-01 12:13 UTC, merged